#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKFLOW="$ROOT/.github/workflows/bootstrap-readbook.yml"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_contains() {
  local needle="$1"
  grep -Fq -- "$needle" "$WORKFLOW" || fail "workflow missing: $needle"
}

assert_not_contains() {
  local needle="$1"
  if grep -Fq -- "$needle" "$WORKFLOW"; then
    fail "workflow should not contain: $needle"
  fi
}

# PRs must restore the cache generated by their base main commit, while main pushes
# save a fresh cache keyed by the newly merged main SHA.
assert_contains 'echo "cache_sha=$GITHUB_SHA" >> "$GITHUB_OUTPUT"'
assert_contains 'echo "cache_sha=$PR_BASE_SHA" >> "$GITHUB_OUTPUT"'
assert_contains '-main-${{ steps.change_scope.outputs.cache_sha }}'
assert_contains 'restore-keys: |'
assert_contains '${{ hashFiles('"'"'Package.resolved'"'"') }}-main-'
assert_contains "github.event_name == 'push' && steps.swiftpm-cache.outputs.cache-hit != 'true'"

# CI should avoid dependency resolution drift and IDE indexing while keeping Release tests.
assert_contains 'swift test -c release'
assert_contains '--only-use-versions-from-resolved-file'
assert_contains '--disable-index-store'
assert_not_contains '--skip-update'

echo "CI workflow cache policy tests passed."
